// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/disaster37/opensearch-handler/v2 (interfaces: OpensearchHandler)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=mocks/opensearch_handler.go -package=mocks github.com/disaster37/opensearch-handler/v2 OpensearchHandler
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	patch "github.com/disaster37/generic-objectmatcher/patch"
	opensearch "github.com/disaster37/opensearch/v2"
	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockOpensearchHandler is a mock of OpensearchHandler interface.
type MockOpensearchHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOpensearchHandlerMockRecorder
}

// MockOpensearchHandlerMockRecorder is the mock recorder for MockOpensearchHandler.
type MockOpensearchHandlerMockRecorder struct {
	mock *MockOpensearchHandler
}

// NewMockOpensearchHandler creates a new mock instance.
func NewMockOpensearchHandler(ctrl *gomock.Controller) *MockOpensearchHandler {
	mock := &MockOpensearchHandler{ctrl: ctrl}
	mock.recorder = &MockOpensearchHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpensearchHandler) EXPECT() *MockOpensearchHandlerMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockOpensearchHandler) Client() *opensearch.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(*opensearch.Client)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockOpensearchHandlerMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockOpensearchHandler)(nil).Client))
}

// ClusterHealth mocks base method.
func (m *MockOpensearchHandler) ClusterHealth() (*opensearch.ClusterHealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterHealth")
	ret0, _ := ret[0].(*opensearch.ClusterHealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterHealth indicates an expected call of ClusterHealth.
func (mr *MockOpensearchHandlerMockRecorder) ClusterHealth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterHealth", reflect.TypeOf((*MockOpensearchHandler)(nil).ClusterHealth))
}

// ComponentTemplateDelete mocks base method.
func (m *MockOpensearchHandler) ComponentTemplateDelete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentTemplateDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComponentTemplateDelete indicates an expected call of ComponentTemplateDelete.
func (mr *MockOpensearchHandlerMockRecorder) ComponentTemplateDelete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentTemplateDelete", reflect.TypeOf((*MockOpensearchHandler)(nil).ComponentTemplateDelete), arg0)
}

// ComponentTemplateDiff mocks base method.
func (m *MockOpensearchHandler) ComponentTemplateDiff(arg0, arg1, arg2 *opensearch.IndicesGetComponentTemplate) (*patch.PatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentTemplateDiff", arg0, arg1, arg2)
	ret0, _ := ret[0].(*patch.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComponentTemplateDiff indicates an expected call of ComponentTemplateDiff.
func (mr *MockOpensearchHandlerMockRecorder) ComponentTemplateDiff(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentTemplateDiff", reflect.TypeOf((*MockOpensearchHandler)(nil).ComponentTemplateDiff), arg0, arg1, arg2)
}

// ComponentTemplateGet mocks base method.
func (m *MockOpensearchHandler) ComponentTemplateGet(arg0 string) (*opensearch.IndicesGetComponentTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentTemplateGet", arg0)
	ret0, _ := ret[0].(*opensearch.IndicesGetComponentTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComponentTemplateGet indicates an expected call of ComponentTemplateGet.
func (mr *MockOpensearchHandlerMockRecorder) ComponentTemplateGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentTemplateGet", reflect.TypeOf((*MockOpensearchHandler)(nil).ComponentTemplateGet), arg0)
}

// ComponentTemplateUpdate mocks base method.
func (m *MockOpensearchHandler) ComponentTemplateUpdate(arg0 string, arg1 *opensearch.IndicesGetComponentTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentTemplateUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComponentTemplateUpdate indicates an expected call of ComponentTemplateUpdate.
func (mr *MockOpensearchHandlerMockRecorder) ComponentTemplateUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentTemplateUpdate", reflect.TypeOf((*MockOpensearchHandler)(nil).ComponentTemplateUpdate), arg0, arg1)
}

// IndexTemplateDelete mocks base method.
func (m *MockOpensearchHandler) IndexTemplateDelete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTemplateDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTemplateDelete indicates an expected call of IndexTemplateDelete.
func (mr *MockOpensearchHandlerMockRecorder) IndexTemplateDelete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTemplateDelete", reflect.TypeOf((*MockOpensearchHandler)(nil).IndexTemplateDelete), arg0)
}

// IndexTemplateDiff mocks base method.
func (m *MockOpensearchHandler) IndexTemplateDiff(arg0, arg1, arg2 *opensearch.IndicesGetIndexTemplate) (*patch.PatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTemplateDiff", arg0, arg1, arg2)
	ret0, _ := ret[0].(*patch.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexTemplateDiff indicates an expected call of IndexTemplateDiff.
func (mr *MockOpensearchHandlerMockRecorder) IndexTemplateDiff(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTemplateDiff", reflect.TypeOf((*MockOpensearchHandler)(nil).IndexTemplateDiff), arg0, arg1, arg2)
}

// IndexTemplateGet mocks base method.
func (m *MockOpensearchHandler) IndexTemplateGet(arg0 string) (*opensearch.IndicesGetIndexTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTemplateGet", arg0)
	ret0, _ := ret[0].(*opensearch.IndicesGetIndexTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexTemplateGet indicates an expected call of IndexTemplateGet.
func (mr *MockOpensearchHandlerMockRecorder) IndexTemplateGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTemplateGet", reflect.TypeOf((*MockOpensearchHandler)(nil).IndexTemplateGet), arg0)
}

// IndexTemplateUpdate mocks base method.
func (m *MockOpensearchHandler) IndexTemplateUpdate(arg0 string, arg1 *opensearch.IndicesGetIndexTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTemplateUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTemplateUpdate indicates an expected call of IndexTemplateUpdate.
func (mr *MockOpensearchHandlerMockRecorder) IndexTemplateUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTemplateUpdate", reflect.TypeOf((*MockOpensearchHandler)(nil).IndexTemplateUpdate), arg0, arg1)
}

// IngestPipelineDelete mocks base method.
func (m *MockOpensearchHandler) IngestPipelineDelete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestPipelineDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestPipelineDelete indicates an expected call of IngestPipelineDelete.
func (mr *MockOpensearchHandlerMockRecorder) IngestPipelineDelete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestPipelineDelete", reflect.TypeOf((*MockOpensearchHandler)(nil).IngestPipelineDelete), arg0)
}

// IngestPipelineDiff mocks base method.
func (m *MockOpensearchHandler) IngestPipelineDiff(arg0, arg1, arg2 *opensearch.IngestGetPipeline) (*patch.PatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestPipelineDiff", arg0, arg1, arg2)
	ret0, _ := ret[0].(*patch.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestPipelineDiff indicates an expected call of IngestPipelineDiff.
func (mr *MockOpensearchHandlerMockRecorder) IngestPipelineDiff(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestPipelineDiff", reflect.TypeOf((*MockOpensearchHandler)(nil).IngestPipelineDiff), arg0, arg1, arg2)
}

// IngestPipelineGet mocks base method.
func (m *MockOpensearchHandler) IngestPipelineGet(arg0 string) (*opensearch.IngestGetPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestPipelineGet", arg0)
	ret0, _ := ret[0].(*opensearch.IngestGetPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestPipelineGet indicates an expected call of IngestPipelineGet.
func (mr *MockOpensearchHandlerMockRecorder) IngestPipelineGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestPipelineGet", reflect.TypeOf((*MockOpensearchHandler)(nil).IngestPipelineGet), arg0)
}

// IngestPipelineUpdate mocks base method.
func (m *MockOpensearchHandler) IngestPipelineUpdate(arg0 string, arg1 *opensearch.IngestGetPipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestPipelineUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestPipelineUpdate indicates an expected call of IngestPipelineUpdate.
func (mr *MockOpensearchHandlerMockRecorder) IngestPipelineUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestPipelineUpdate", reflect.TypeOf((*MockOpensearchHandler)(nil).IngestPipelineUpdate), arg0, arg1)
}

// SetLogger mocks base method.
func (m *MockOpensearchHandler) SetLogger(arg0 *logrus.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", arg0)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockOpensearchHandlerMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockOpensearchHandler)(nil).SetLogger), arg0)
}

// SnapshotRepositoryDelete mocks base method.
func (m *MockOpensearchHandler) SnapshotRepositoryDelete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotRepositoryDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SnapshotRepositoryDelete indicates an expected call of SnapshotRepositoryDelete.
func (mr *MockOpensearchHandlerMockRecorder) SnapshotRepositoryDelete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotRepositoryDelete", reflect.TypeOf((*MockOpensearchHandler)(nil).SnapshotRepositoryDelete), arg0)
}

// SnapshotRepositoryDiff mocks base method.
func (m *MockOpensearchHandler) SnapshotRepositoryDiff(arg0, arg1, arg2 *opensearch.SnapshotRepositoryMetaData) (*patch.PatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotRepositoryDiff", arg0, arg1, arg2)
	ret0, _ := ret[0].(*patch.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotRepositoryDiff indicates an expected call of SnapshotRepositoryDiff.
func (mr *MockOpensearchHandlerMockRecorder) SnapshotRepositoryDiff(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotRepositoryDiff", reflect.TypeOf((*MockOpensearchHandler)(nil).SnapshotRepositoryDiff), arg0, arg1, arg2)
}

// SnapshotRepositoryGet mocks base method.
func (m *MockOpensearchHandler) SnapshotRepositoryGet(arg0 string) (*opensearch.SnapshotRepositoryMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotRepositoryGet", arg0)
	ret0, _ := ret[0].(*opensearch.SnapshotRepositoryMetaData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotRepositoryGet indicates an expected call of SnapshotRepositoryGet.
func (mr *MockOpensearchHandlerMockRecorder) SnapshotRepositoryGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotRepositoryGet", reflect.TypeOf((*MockOpensearchHandler)(nil).SnapshotRepositoryGet), arg0)
}

// SnapshotRepositoryUpdate mocks base method.
func (m *MockOpensearchHandler) SnapshotRepositoryUpdate(arg0 string, arg1 *opensearch.SnapshotRepositoryMetaData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotRepositoryUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SnapshotRepositoryUpdate indicates an expected call of SnapshotRepositoryUpdate.
func (mr *MockOpensearchHandlerMockRecorder) SnapshotRepositoryUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotRepositoryUpdate", reflect.TypeOf((*MockOpensearchHandler)(nil).SnapshotRepositoryUpdate), arg0, arg1)
}
